# Generated by Django 3.2.10 on 2023-07-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_model', models.CharField(max_length=200)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('cat_discription', models.CharField(max_length=500)),
            ],
        ),
    ]
