# Generated by Django 3.2.10 on 2023-07-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxuaryvillaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='cat_discription',
            new_name='cat_description',
        ),
    ]
