# Generated by Django 3.2.10 on 2023-08-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxuaryvillaApp', '0002_rename_cat_discription_categorydb_cat_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('Pro_name', models.CharField(max_length=100)),
                ('ProductImage', models.ImageField(null=True, upload_to='image')),
                ('Prize', models.IntegerField(null=True)),
                ('ProDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='categorydb',
            name='cat_image',
        ),
        migrations.RemoveField(
            model_name='categorydb',
            name='cat_model',
        ),
        migrations.AddField(
            model_name='categorydb',
            name='categoryImage',
            field=models.ImageField(null=True, upload_to='cimage'),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='cat_description',
            field=models.CharField(max_length=100),
        ),
    ]
