# Generated by Django 3.2.10 on 2023-08-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxuaryvillaApp', '0003_auto_20230807_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='cat_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='cat_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productdb',
            name='Prize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdb',
            name='ProDescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productdb',
            name='Pro_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productdb',
            name='c_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
