# Generated by Django 3.2.10 on 2023-08-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxuaryvillaApp', '0004_auto_20230808_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydb',
            name='Location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
