# Generated by Django 3.2.10 on 2023-08-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxuaryvillaApp', '0005_categorydb_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Prize',
            new_name='Price',
        ),
    ]
