# Generated by Django 3.2.10 on 2023-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxuaryvillaApp', '0006_rename_prize_productdb_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentsDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Agent_id', models.IntegerField(blank=True, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
