# Generated by Django 3.2.10 on 2023-09-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_bookslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnum', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('cardnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('expire', models.CharField(blank=True, max_length=50, null=True)),
                ('cvv', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
